services:
  db: 
    image: postgres:16
    env_file:
      - ./.env
    container_name: store_db
    restart: unless-stopped
    ports:
      - "5440:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./backups:/backups
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: store_pgadmin
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5051:80"
    depends_on:
      - db
  app:
    build: .
    container_name: webstore_app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db

